// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TCompanyColumns holds the columns for the "t_company" table.
	TCompanyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_name", Type: field.TypeString},
		{Name: "contract_phone", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// TCompanyTable holds the schema information for the "t_company" table.
	TCompanyTable = &schema.Table{
		Name:       "t_company",
		Columns:    TCompanyColumns,
		PrimaryKey: []*schema.Column{TCompanyColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "t_company_t_user_companys",
				Columns:    []*schema.Column{TCompanyColumns[3]},
				RefColumns: []*schema.Column{TUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TPersonalColumns holds the columns for the "t_personal" table.
	TPersonalColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// TPersonalTable holds the schema information for the "t_personal" table.
	TPersonalTable = &schema.Table{
		Name:       "t_personal",
		Columns:    TPersonalColumns,
		PrimaryKey: []*schema.Column{TPersonalColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "t_personal_t_user_personals",
				Columns:    []*schema.Column{TPersonalColumns[3]},
				RefColumns: []*schema.Column{TUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TUserColumns holds the columns for the "t_user" table.
	TUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_name", Type: field.TypeJSON},
		{Name: "password", Type: field.TypeJSON},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
	}
	// TUserTable holds the schema information for the "t_user" table.
	TUserTable = &schema.Table{
		Name:       "t_user",
		Columns:    TUserColumns,
		PrimaryKey: []*schema.Column{TUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "t_user_t_user_children",
				Columns:    []*schema.Column{TUserColumns[3]},
				RefColumns: []*schema.Column{TUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TCompanyTable,
		TPersonalTable,
		TUserTable,
	}
)

func init() {
	TCompanyTable.ForeignKeys[0].RefTable = TUserTable
	TCompanyTable.Annotation = &entsql.Annotation{
		Table: "t_company",
	}
	TPersonalTable.ForeignKeys[0].RefTable = TUserTable
	TPersonalTable.Annotation = &entsql.Annotation{
		Table: "t_personal",
	}
	TUserTable.ForeignKeys[0].RefTable = TUserTable
	TUserTable.Annotation = &entsql.Annotation{
		Table: "t_user",
	}
}
