// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbCompanyColumns holds the columns for the "tb_company" table.
	TbCompanyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_name", Type: field.TypeString},
		{Name: "contract_phone", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// TbCompanyTable holds the schema information for the "tb_company" table.
	TbCompanyTable = &schema.Table{
		Name:       "tb_company",
		Columns:    TbCompanyColumns,
		PrimaryKey: []*schema.Column{TbCompanyColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tb_company_tb_user_companys",
				Columns:    []*schema.Column{TbCompanyColumns[3]},
				RefColumns: []*schema.Column{TbUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TbPersonalColumns holds the columns for the "tb_personal" table.
	TbPersonalColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// TbPersonalTable holds the schema information for the "tb_personal" table.
	TbPersonalTable = &schema.Table{
		Name:       "tb_personal",
		Columns:    TbPersonalColumns,
		PrimaryKey: []*schema.Column{TbPersonalColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tb_personal_tb_user_personals",
				Columns:    []*schema.Column{TbPersonalColumns[3]},
				RefColumns: []*schema.Column{TbUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TbUserColumns holds the columns for the "tb_user" table.
	TbUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
	}
	// TbUserTable holds the schema information for the "tb_user" table.
	TbUserTable = &schema.Table{
		Name:       "tb_user",
		Columns:    TbUserColumns,
		PrimaryKey: []*schema.Column{TbUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tb_user_tb_user_children",
				Columns:    []*schema.Column{TbUserColumns[3]},
				RefColumns: []*schema.Column{TbUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbCompanyTable,
		TbPersonalTable,
		TbUserTable,
	}
)

func init() {
	TbCompanyTable.ForeignKeys[0].RefTable = TbUserTable
	TbCompanyTable.Annotation = &entsql.Annotation{
		Table: "tb_company",
	}
	TbPersonalTable.ForeignKeys[0].RefTable = TbUserTable
	TbPersonalTable.Annotation = &entsql.Annotation{
		Table: "tb_personal",
	}
	TbUserTable.ForeignKeys[0].RefTable = TbUserTable
	TbUserTable.Annotation = &entsql.Annotation{
		Table: "tb_user",
	}
}
